/*
 * Copyright (c) AudioManager Project Contributors.
 * SPDX-License-Identifier: Apache-2.0
 */
package audiomanager.core;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 * Writes ID3 tags to audio files after transcription.
 * This is a lightweight implementation that creates a sidecar file
 * with metadata, as the project currently has no MP3 tagging library.
 */
public class ID3TagWriter {

    private static final Logger LOGGER = LoggerFactory.getLogger(ID3TagWriter.class);

    /**
     * Write ID3 tags to an audio file.
     * Since we don't have a proper ID3 library, this creates a sidecar
     * metadata file (.meta) that can be read by audio players.
     */
    public static void writeTags(File audioFile, String title, String artist, 
                                  String album, String language) throws IOException {
        Path metaPath = Paths.get(audioFile.getAbsolutePath() + ".meta");
        
        StringBuilder content = new StringBuilder();
        content.append("[ID3 Metadata]\n");
        content.append("File: ").append(audioFile.getName()).append("\n");
        content.append("Title: ").append(title != null ? title : "").append("\n");
        content.append("Artist: ").append(artist != null ? artist : "AudioManager").append("\n");
        content.append("Album: ").append(album != null ? album : "Transcriptions").append("\n");
        content.append("Language: ").append(language != null ? language : "auto").append("\n");
        content.append("Date: ").append(java.time.LocalDate.now()).append("\n");
        content.append("Comment: Generated by AudioManager\n");
        content.append("Software: AudioManager v").append(System.getProperty("app.version", "3.9")).append("\n");

        Files.writeString(metaPath, content);
        LOGGER.info("Metadata written to: {}", metaPath);
    }

    /**
     * Write tags from a TranscriptionResult.
     */
    public static void writeTagsFromTranscription(File audioFile, 
                                                   audiomanager.model.TranscriptionResult result) 
            throws IOException {
        String title = audioFile.getName().replaceFirst("\\.[^.]+$", "");
        String artist = "AudioManager";
        String album = "Transcriptions";
        String language = result.getLanguage() != null ? result.getLanguage() : "auto";
        writeTags(audioFile, title, artist, album, language);
    }
}