/*
 * Copyright (c) AudioManager Project Contributors.
 * SPDX-License-Identifier: Apache-2.0
 */
package audiomanager.core;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 * Writes ID3 tags and metadata to audio files after transcription.
 *
 * <p>This class provides a lightweight metadata writing implementation that
 * creates sidecar metadata files (with a {@code .meta} extension) containing
 * information about the transcription. This approach is used because the
 * project currently has no MP3 tagging library dependency.</p>
 *
 * <p><b>Metadata written:</b>
 * <ul>
 *   <li>File name</li>
 *   <li>Title (derived from file name)</li>
 *   <li>Artist (default: "AudioManager")</li>
 *   <li>Album (default: "Transcriptions")</li>
 *   <li>Language (from transcription result)</li>
 *   <li>Date of generation</li>
 *   <li>Software version</li>
 * </ul>
 *
 * <p><b>Future enhancement:</b> When a proper ID3 library (e.g., jaudiotagger)
 * is added to the project, this class can be extended to write actual
 * ID3 tags into audio files directly.</p>
 *
 * @author AudioManager Project Contributors
 * @version 4.0.0
 * @see TranscriptionResult
 */
public class ID3TagWriter {

    private static final Logger LOGGER = LoggerFactory.getLogger(ID3TagWriter.class);

    /**
     * Writes ID3 tags to an audio file as a sidecar metadata file.
     *
     * <p>Since a proper ID3 library is not available, this method creates
     * a sidecar metadata file ({@code .meta}) that can be read by audio
     * players or used for reference.</p>
     *
     * @param audioFile the audio file to tag
     * @param title the title of the audio (may be {@code null})
     * @param artist the artist name (may be {@code null})
     * @param album the album name (may be {@code null})
     * @param language the language code (may be {@code null})
     * @throws IOException if the metadata file cannot be written
     */
    public static void writeTags(File audioFile, String title, String artist,
                                  String album, String language) throws IOException {
        Path metaPath = Paths.get(audioFile.getAbsolutePath() + ".meta");

        StringBuilder content = new StringBuilder();
        content.append("[ID3 Metadata]\n");
        content.append("File: ").append(audioFile.getName()).append("\n");
        content.append("Title: ").append(title != null ? title : "").append("\n");
        content.append("Artist: ").append(artist != null ? artist : "AudioManager").append("\n");
        content.append("Album: ").append(album != null ? album : "Transcriptions").append("\n");
        content.append("Language: ").append(language != null ? language : "auto").append("\n");
        content.append("Date: ").append(java.time.LocalDate.now()).append("\n");
        content.append("Comment: Generated by AudioManager\n");
        content.append("Software: AudioManager v").append(System.getProperty("app.version", "3.9")).append("\n");

        Files.writeString(metaPath, content);
        LOGGER.info("Metadata written to: {}", metaPath);
    }

    /**
     * Writes metadata from a transcription result to an audio file.
     *
     * <p>This convenience method extracts the title from the audio file name
     * and the language from the transcription result.</p>
     *
     * @param audioFile the audio file to tag
     * @param result the transcription result containing language information
     * @throws IOException if the metadata file cannot be written
     */
    public static void writeTagsFromTranscription(File audioFile,
                                                   audiomanager.model.TranscriptionResult result)
            throws IOException {
        String title = audioFile.getName().replaceFirst("\\.[^.]+$", "");
        String artist = "AudioManager";
        String album = "Transcriptions";
        String language = result.getLanguage() != null ? result.getLanguage() : "auto";
        writeTags(audioFile, title, artist, album, language);
    }
}